# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  publish = "build/"
  command = "npm run build"

[build.environment]
  NODE_PATH = "./src"
  REACT_APP_GA_ID = "UA-85981-5"
  REACT_APP_GOOGLE_VERIFICATION = "EJOTQWsVwuMA6tjtdmDXM0v8ejx4G12gMnu9MKnT5f4"
  REACT_APP_TYPEKIT_ID = "tgw1nyv"
